name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up swift
      uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: 6.2

    - name: Print Swift version
      run: swift --version
    
    - name: Restore Cache for SPM
      if: ${{ matrix.build-system == 'spm' }}
      uses: actions/cache@v4
      with:
        path: .build
        key: devcontainer-${{ matrix.config }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Run tests
      run: swift test

